### ISSUE TITLE
MLF Date-A-Scientist Grade Summary

### ISSUE THREAD

**Issue by mackenzieyoung** [jeanpaolo/date-a-scientist#1]
### Criteria 1: Valid Python Code
* _Score Level:_ NA 
* _Comment(s):_ Please upload your code, and I'll update this
 
### Criteria 2: Exploration of Data
* _Score Level:_ 2 (Approaches expectations)
* _Comment(s):_ You do explore the data briefly, but your experimental questions are not related to your data exploration. In general, you want your data exploration to inform your research questions, because the initial data exploration can give you an idea about which questions are worth asking (e.g., does there appear to be a relationship between two variables?)
 
### Criteria 3: Machine Learning Techniques used correctly
* _Score Level:_ 3 (Meets expectations)
* _Comment(s):_ You're right that using ethnicity as an independent variable in your linear regression wasn't the right choice, but I'm wondering why you did it anyway! I also would have liked a little more discussion about your classification algorithms.

### Criteria 4: Report: Are conclusions clear and supported by data?
* _Score Level:_ 2 (Approaches expectations)
* _Comment(s):_ Your research questions could be stated more clearly, for example in your second question, when you say "using the words of all their essays," what exactly are you looking at? Do you mean the average essay length of each person? If so, how did you account for essays questions that weren't answered -- did you count those as zero, or did you just not include them in your average, and why did you make that decision? Or did you use total number of words across all essays? In general when you analyze your model results, you should look at more than just accuracy (but in your case your regression models performed so poorly that looking at accuracy may be enough, but the poor performance could have been avoided with more data exploration!)

### Criteria 5: Code formatting
* _Score Level:_ NA
* _Comment(s):_ Again, please upload your code!
 
### Overall Score: 7/20

**Comment by jeanpaolo** [comment]
Hi Mackenzie,

Thank you for the review. I apologize I did not know what was clearly expected of me in this project.
re: data exploration - I assumed I was looking for interesting data and not data directly related to the question. My mistake.

Can I re submit my presentation again if that is still possible?
I will upload my code after this comment.

Thank you!

**Comment by mackenzieyoung** [comment]
That's okay! In general, what you want from data exploration is to learn about your data in a way that informs your research questions. Thanks for uploading your code, I just updated my comment to reflect that! No need to resubmit your presentation again.
